replicaCount: 2
image:
  tag: stable-alpine
ingress:
  enabled: false
  className: "nginx"
    #annotations: 
    #nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    #nginx.ingress.kubernetes.io/ssl-redirect: true
    
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: staging.sample.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

