apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-app-production
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/T1kcan/argo-helm-gitops.git
    targetRevision: main
    path: charts/sample-app
    helm:
      valueFiles:
        - ../../environments/production/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: production
  syncPolicy:
    automated:
      prune: truespec:
  strategy:
    canary:
      analysis:
        templates:
          - templateName: success-rate-check
      steps:
        - setWeight: 20
        - pause: {duration: 5m} 
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
